

mycorners.cornerlist("wood_black",         "corners_wood_black.png",          "Black Wood")
mycorners.cornerlist("wood_blue",  	       "corners_wood_blue.png",           "Blue Wood")
mycorners.cornerlist("wood_brown", 	       "corners_wood_brown.png",          "Brown Wood")
mycorners.cornerlist("wood_cyan",  	       "corners_wood_cyan.png",           "Cyan Wood")
mycorners.cornerlist("wood_dark_green",    "corners_wood_dark_green.png",     "Dark Green Wood")
mycorners.cornerlist("wood_dark_grey",     "corners_wood_dark_grey.png",      "Dark Grey Wood")
mycorners.cornerlist("wood_green",         "corners_wood_green.png",          "Green Wood")
mycorners.cornerlist("wood_grey",  	       "corners_wood_grey.png",           "Grey Wood")
mycorners.cornerlist("wood_magenta",       "corners_wood_magenta.png",        "Magenta Wood")
mycorners.cornerlist("wood_orange",        "corners_wood_orange.png",         "Orange Wood")
mycorners.cornerlist("wood_pink", 	       "corners_wood_pink.png",           "Pink Wood")
mycorners.cornerlist("wood_red", 	       "corners_wood_red.png",            "Red Wood")
mycorners.cornerlist("wood_violet",        "corners_wood_violet.png",         "Violet Wood")
mycorners.cornerlist("wood_white", 	       "corners_wood_white.png",          "White Wood")
mycorners.cornerlist("wood_yellow",        "corners_wood_yellow.png",         "Yellow Wood")
mycorners.cornerlist("stone_black",           "corners_stone_black.png",          "Black Stone")
mycorners.cornerlist("stone_blue",  	  "corners_stone_blue.png",           "Blue Brick")
mycorners.cornerlist("stone_brown",           "corners_stone_brown.png",          "Brown Stone")
mycorners.cornerlist("stone_cyan",            "corners_stone_cyan.png",           "Cyan Stone")
mycorners.cornerlist("stone_dark_green",      "corners_stone_dark_green.png",     "Dark Green Stone")
mycorners.cornerlist("stone_dark_grey",       "corners_stone_dark_grey.png",      "Dark Grey Stone")
mycorners.cornerlist("stone_green",           "corners_stone_green.png",          "Green Stone")
mycorners.cornerlist("stone_grey",            "corners_stone_grey.png",           "Grey Stone")
mycorners.cornerlist("stone_magenta",         "corners_stone_magenta.png",        "Magenta Stone")
mycorners.cornerlist("stone_orange",          "corners_stone_orange.png",         "Orange Stone")
mycorners.cornerlist("stone_pink", 	          "corners_stone_pink.png",           "Pink Stone")
mycorners.cornerlist("stone_red", 	          "corners_stone_red.png",            "Red Stone")
mycorners.cornerlist("stone_violet",          "corners_stone_violet.png",         "Violet Stone")
mycorners.cornerlist("stone_white",           "corners_stone_white.png",          "White Stone")
mycorners.cornerlist("stone_yellow",          "corners_stone_yellow.png",         "Yellow Stone")
mycorners.cornerlist("stonebrick_black",          "corners_stonebrick_black.png",          "Black Stone Brick")
mycorners.cornerlist("stonebrick_blue",  	      "corners_stonebrick_blue.png",           "Blue Stone Brick")
mycorners.cornerlist("stonebrick_brown", 	      "corners_stonebrick_brown.png",          "Brown Stone Brick")
mycorners.cornerlist("stonebrick_cyan",  	      "corners_stonebrick_cyan.png",           "Cyan Stone Brick")
mycorners.cornerlist("stonebrick_dark_green",     "corners_stonebrick_dark_green.png",     "Dark Green Stone Brick")
mycorners.cornerlist("stonebrick_dark_grey",      "corners_stonebrick_dark_grey.png",      "Dark Grey Stone Brick")
mycorners.cornerlist("stonebrick_green",          "corners_stonebrick_green.png",          "Green Stone Brick")
mycorners.cornerlist("stonebrick_grey",  	      "corners_stonebrick_grey.png",           "Grey Stone Brick")
mycorners.cornerlist("stonebrick_magenta",        "corners_stonebrick_magenta.png",        "Magenta Stone Brick")
mycorners.cornerlist("stonebrick_orange",         "corners_stonebrick_orange.png",         "Orange Stone Brick")
mycorners.cornerlist("stonebrick_pink", 	      "corners_stonebrick_pink.png",           "Pink Stone Brick")
mycorners.cornerlist("stonebrick_red", 	      "corners_stonebrick_red.png",            "Red Stone Brick")
mycorners.cornerlist("stonebrick_violet",         "corners_stonebrick_violet.png",         "Violet Stone Brick")
mycorners.cornerlist("stonebrick_white", 	      "corners_stonebrick_white.png",          "White Stone Brick")
mycorners.cornerlist("stonebrick_yellow",         "corners_stonebrick_yellow.png",         "Yellow Stone Brick")


